import React, { useEffect, useRef, useState } from 'react';
import './GenesisMoment.css';
const GRID_SIZE = 32; const NODE_COUNT = 64;
const GenesisMoment = ({ userCredentials, targetServer, onTeleportComplete }) => {
  const canvasRef = useRef(null);
  const [phase, setPhase] = useState('blueprint');
  const [progress, setProgress] = useState(0);
  const nodesRef = useRef([]);
  const animationRef = useRef(null);
  useEffect(() => { const nodes = []; for (let i = 0; i < NODE_COUNT; i++) { nodes.push({ x: Math.random() * 100, y: Math.random() * 100, z: Math.random() * 50, connections: [], pulse: Math.random() * Math.PI * 2, speed: 0.5 + Math.random() * 1.5 }); } nodes.forEach((node, i) => { const others = nodes.map((n, idx) => ({ idx, dist: Math.hypot(n.x - node.x, n.y - node.y) })).filter(n => n.dist > 0 && n.dist < 25); others.sort((a,b) => a.dist - b.dist).slice(0, 3).forEach(o => node.connections.push(o.idx)); }); nodesRef.current = nodes; }, []);
  useEffect(() => { const canvas = canvasRef.current; const ctx = canvas.getContext('2d'); let frame = 0; const resize = () => { canvas.width = window.innerWidth; canvas.height = window.innerHeight; }; resize(); window.addEventListener('resize', resize); const draw = () => { ctx.fillStyle = '#0a0e17'; ctx.fillRect(0, 0, canvas.width, canvas.height); const w = canvas.width, h = canvas.height, nodes = nodesRef.current, time = frame * 0.016; ctx.strokeStyle = phase === 'blueprint' ? 'rgba(0, 255, 242, 0.15)' : 'rgba(0, 255, 242, 0.05)'; ctx.lineWidth = 0.5; const gs = w / GRID_SIZE; for (let i = 0; i <= GRID_SIZE; i++) { const dp = Math.min(1, progress * 1.5); ctx.beginPath(); ctx.moveTo(i*gs, 0); ctx.lineTo(i*gs, h*dp); ctx.stroke(); ctx.beginPath(); ctx.moveTo(0, i*(h/GRID_SIZE)); ctx.lineTo(w*dp, i*(h/GRID_SIZE)); ctx.stroke(); } nodes.forEach((node, i) => { const nx = (node.x/100)*w, ny = (node.y/100)*h, pulse = Math.sin(time*node.speed+node.pulse)*0.5+0.5; const g = ctx.createRadialGradient(nx, ny, 0, nx, ny, phase === 'blueprint' ? 4+pulse*4 : 2); g.addColorStop(0, 'rgba(0, 255, 242, 0.9)'); g.addColorStop(1, 'rgba(0, 255, 242, 0)'); ctx.fillStyle = g; ctx.beginPath(); ctx.arc(nx, ny, phase === 'blueprint' ? 6 : 3, 0, Math.PI*2); ctx.fill(); if (phase === 'blueprint' || phase === 'construct') { node.connections.forEach(tIdx => { const t = nodes[tIdx], tx = (t.x/100)*w, ty = (t.y/100)*h; ctx.strokeStyle = `rgba(0, 255, 242, ${0.3*pulse*progress})`; ctx.lineWidth = 0.8; ctx.beginPath(); ctx.moveTo(nx, ny); if (phase === 'construct') { const mx = (nx+tx)/2+Math.sin(time+i)*30, my = (ny+ty)/2+Math.cos(time+i)*30; ctx.quadraticCurveTo(mx, my, tx, ty); } else { ctx.lineTo(tx, ty); } ctx.stroke(); }); } }); if (phase === 'solidify' || phase === 'teleport') { ctx.fillStyle = `rgba(0, 255, 242, ${0.02*progress})`; ctx.fillRect(0, 0, w, h); const sy = (1-progress)*h; ctx.strokeStyle = 'rgba(0, 255, 242, 0.6)'; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(0, sy); ctx.lineTo(w, sy); ctx.stroke(); } if (phase === 'teleport') { const cx = w/2, cy = h/2, mr = Math.hypot(cx, cy), vp = (progress-0.7)/0.3; for (let r = 0; r < 5; r++) { const radius = mr*(1-vp)*(1-r*0.15), rot = time*2+r*1.5; ctx.save(); ctx.translate(cx, cy); ctx.rotate(rot); ctx.strokeStyle = `rgba(0, 255, 242, ${vp*0.4})`; ctx.lineWidth = 2; ctx.strokeRect(-radius, -radius, radius*2, radius*2); ctx.restore(); } } frame++; animationRef.current = requestAnimationFrame(draw); }; draw(); return () => { cancelAnimationFrame(animationRef.current); window.removeEventListener('resize', resize); }; }, [phase, progress]);
  useEffect(() => { const phases = [{name:'blueprint',d:3000},{name:'construct',d:4000},{name:'solidify',d:3000},{name:'teleport',d:2500}]; let cp = 0, st = Date.now(); const iv = setInterval(() => { const e = Date.now()-st, pd = phases[cp], pp = Math.min(1, e/pd.d); setPhase(pd.name); setProgress(pp); if (pp >= 1) { cp++; st = Date.now(); if (cp >= phases.length) { clearInterval(iv); onTeleportComplete?.(); } } }, 16); return () => clearInterval(iv); }, [onTeleportComplete]);
  return (<div className="genesis-moment"><canvas ref={canvasRef} className="genesis-canvas" /><div className={`genesis-ui ${phase}`}><div className="credential-pill"><span className="label">SOVEREIGN</span><span className="value">{userCredentials?.handle || 'Unknown'}</span></div><div className="status-line">{phase==='blueprint'&&'INITIALIZING BLUEPRINT MATRIX...'}{phase==='construct'&&'CONSTRUCTING SPATIAL GEOMETRY...'}{phase==='solidify'&&'MATERIALIZING SOVEREIGN DOMAIN...'}{phase==='teleport'&&`ESTABLISHING UPLINK TO ${targetServer?.name||'SERVER'}...`}</div><div className="progress-rail"><div className="progress-fill" style={{width:`${progress*100}%`}} /></div><div className="data-stream">{Array.from({length:8}).map((_,i)=>(<span key={i} className="data-bit" style={{animationDelay:`${i*0.1}s`}}>{Math.random().toString(36).substring(2,8).toUpperCase()}</span>))}</div></div></div>);
};
export default GenesisMoment;